//
//  DetailsInterfaces.swift
//  itunesapi
//
//  Created by Alejandro Melo Domínguez on 08-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailsNavigationOption {
    case preview(Media)
}

protocol DetailsWireframeInterface: WireframeInterface {
    func navigate(to option: DetailsNavigationOption)
}

protocol DetailsViewInterface: ViewInterface {
    var album: Media? { get set }
    var tracks: [Media]? { get set }
}

protocol DetailsPresenterInterface: PresenterInterface {
    func loadAlbumDetails(item: Media)
    func successFetchingAlbum(album: Album)
    func failureFetchingAlbum(error: Error?)
    
    func didSelect(item: Media)
}

protocol DetailsInteractorInterface: InteractorInterface {
    func fetchAlbumDetails(for item: Media)
}
