//
//  DetailsWireframe.swift
//  itunesapi
//
//  Created by Alejandro Melo Domínguez on 08-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DetailsWireframe: BaseWireframe {

    // MARK: - Private properties -

    private let _storyboard = UIStoryboard(name: "Details", bundle: nil)

    // MARK: - Module setup -

    init(media: Media) {
        let moduleViewController = _storyboard.instantiateViewController(ofType: DetailsViewController.self)
        super.init(viewController: moduleViewController)
        
        let interactor = DetailsInteractor()
        let presenter = DetailsPresenter(wireframe: self, view: moduleViewController, interactor: interactor)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DetailsWireframe: DetailsWireframeInterface {

    func navigate(to option: DetailsNavigationOption) {
    }
}
