//
//  DetailsInteractor.swift
//  itunesapi
//
//  Created by Alejandro Melo Domínguez on 08-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DetailsInteractor {
}

// MARK: - Extensions -

extension DetailsInteractor: DetailsInteractorInterface {
}
