//
//  DetailsInterfaces.swift
//  itunesapi
//
//  Created by Alejandro Melo Domínguez on 08-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum DetailsNavigationOption {
}

protocol DetailsWireframeInterface: WireframeInterface {
    func navigate(to option: DetailsNavigationOption)
}

protocol DetailsViewInterface: ViewInterface {
}

protocol DetailsPresenterInterface: PresenterInterface {
}

protocol DetailsInteractorInterface: InteractorInterface {
}
