//
//  PreviewPlayerInteractor.swift
//  itunesapi
//
//  Created by dpsmac1 on 09-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class PreviewPlayerInteractor {
    weak var presenter: PreviewPlayerPresenter!
}

// MARK: - Extensions -

extension PreviewPlayerInteractor: PreviewPlayerInteractorInterface {
}
