//
//  PreviewPlayerViewController.swift
//  itunesapi
//
//  Created by dpsmac1 on 09-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import AlamofireImage

final class PreviewPlayerViewController: UIViewController {

    // MARK: - Private properties -
    @IBOutlet private weak var coverImageView: UIImageView!
    @IBOutlet private weak var trackNameLabel: UILabel!
    @IBOutlet private weak var playerContainerView: UIView!
    
    
    // MARK: - Public properties -

    var presenter: PreviewPlayerPresenterInterface!
    var item: Media? {
        didSet {
            reloadData()
        }
    }

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        setupBlurEffect()
        
        presenter.viewDidLoad()
    }
	
    @IBAction func closePopup() {
        dismiss(animated: true) {
            self.presenter.didClosePreviewPlayer()
        }
    }
    
}

// MARK: - Extensions -

extension PreviewPlayerViewController: PreviewPlayerViewInterface {
}




// MARK: - Update UI
extension PreviewPlayerViewController {
    fileprivate func reloadData() {
        guard let item = item, let imageURL = item.urlForArtwork, let previewURL = item.urlForPreview else {
            return
        }
        
        /*
         El seteo de la imagen debería ser instantáneo, ya que se obtuvo
         en DetailsViewController y Alamofire cachea la respuesta.
         */
        coverImageView.af_cancelImageRequest()
        coverImageView.af_setImage(withURL: imageURL)
        
        trackNameLabel.text = item.trackName
    }
}




// MARK: - Blur effect
extension PreviewPlayerViewController {
    fileprivate func setupBlurEffect() {
        // Background blur yeeey
        let blurEffect = UIBlurEffect(style: .dark)
        let blurEffectView = UIVisualEffectView(effect: blurEffect)
        blurEffectView.frame = view.bounds
        
        view.addSubview(blurEffectView)
        view.sendSubview(toBack: blurEffectView)
    }
}
