//
//  PreviewPlayerPresenter.swift
//  itunesapi
//
//  Created by dpsmac1 on 09-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class PreviewPlayerPresenter {

    // MARK: - Private properties -

    private unowned var _view: PreviewPlayerViewInterface
    private var _interactor: PreviewPlayerInteractorInterface
    private var _wireframe: PreviewPlayerWireframeInterface
    private let song: Media

    // MARK: - Lifecycle -

    init(wireframe: PreviewPlayerWireframeInterface, view: PreviewPlayerViewInterface, interactor: PreviewPlayerInteractorInterface, song: Media) {
        _wireframe = wireframe
        _view = view
        _interactor = interactor
        self.song = song
    }
    
    func viewDidLoad() {
        _view.item = song
    }
}

// MARK: - Extensions -

// MARK: Close player
extension PreviewPlayerPresenter: PreviewPlayerPresenterInterface {
    func didClosePreviewPlayer() {
        
    }
}




// MARK: Playback
extension PreviewPlayerPresenter {
    func playPreview(_ url: URL) {
        
    }
    
    func stopPreview() {
        
    }
}
