//
//  PreviewPlayerInterfaces.swift
//  itunesapi
//
//  Created by dpsmac1 on 09-05-18.
//  Copyright (c) 2018 Alejandro Iván. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum PreviewPlayerNavigationOption {
}

protocol PreviewPlayerWireframeInterface: WireframeInterface {
    func navigate(to option: PreviewPlayerNavigationOption)
}

protocol PreviewPlayerViewInterface: ViewInterface {
    var item: Media? { get set }
}

protocol PreviewPlayerPresenterInterface: PresenterInterface {
    func didClosePreviewPlayer()
    
    func playPreview(_ url: URL)
    func stopPreview()
}

protocol PreviewPlayerInteractorInterface: InteractorInterface {
}
